### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/blueprints-learn.en#6]
Issue in ./help/blueprints/customer-journeys/3rd-party-messaging.md

The link for "[Adobe Journey Optimizer Mobile Guide](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-journey-optimizer)" is broken. It returns a 404 error.

**Comment by bbringhu** [comment]
Thanks for reporting this issue. We have updated the link.
